name: Deploy To Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy To Heroku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Secrets Variables
        working-directory: ./
        run: |
          sed -i "s/GH_SECRETS_OPEN_SOURCE_TOKEN/${{secrets.OPEN_SOURCE_TOKEN}}/g" protected/secrets.py
          sed -i "s/GH_SECRETS_GUILD_ID/${{secrets.GUILD_ID}}/g" protected/secrets.py
      - name: Deploy To Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
